version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: honda
      POSTGRES_PASSWORD: honda
      POSTGRES_DB: honda_internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=honda
      - POSTGRES_PASSWORD=honda
      - POSTGRES_DB=honda_internal
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_ORIGINS=["http://localhost:5173"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    depends_on:
      - backend

  worker:
    build:
      context: ./backend
    command: poetry run celery -A app.tasks worker --loglevel=info
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:
