services:
  - type: web
    name: vehicle-inventory-backend
    env: python
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install poetry && poetry install --no-interaction --no-root
    startCommand: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
