name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      DATABASE_URL: sqlite+aiosqlite:///./test.db
      REDIS_URL: redis://localhost:6379/0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==2.2.1
          python -m poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: python -m poetry install --no-interaction --no-root

      - name: Run tests
        run: python -m poetry run pytest --maxfail=1 --disable-warnings -q
